// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeYl4IKFpNr1wHiKXajPK0J4IV9lpvykI',
    appId: '1:610579116609:web:c8ef1afb8e7256d4844cc0',
    messagingSenderId: '610579116609',
    projectId: 'tubitak-akran-zorbaligi',
    authDomain: 'tubitak-akran-zorbaligi.firebaseapp.com',
    storageBucket: 'tubitak-akran-zorbaligi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPKt4kqHvzKLBuxsbpF4qd1NQTRd_XcWY',
    appId: '1:610579116609:android:4536b4cc1cc2ce6e844cc0',
    messagingSenderId: '610579116609',
    projectId: 'tubitak-akran-zorbaligi',
    storageBucket: 'tubitak-akran-zorbaligi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIY3Ths6aKjO-zzHiwgZCqs6B6ueX4tuc',
    appId: '1:610579116609:ios:8eacfd427be17a7a844cc0',
    messagingSenderId: '610579116609',
    projectId: 'tubitak-akran-zorbaligi',
    storageBucket: 'tubitak-akran-zorbaligi.firebasestorage.app',
    iosBundleId: 'com.example.zorbalikUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIY3Ths6aKjO-zzHiwgZCqs6B6ueX4tuc',
    appId: '1:610579116609:ios:8eacfd427be17a7a844cc0',
    messagingSenderId: '610579116609',
    projectId: 'tubitak-akran-zorbaligi',
    storageBucket: 'tubitak-akran-zorbaligi.firebasestorage.app',
    iosBundleId: 'com.example.zorbalikUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeYl4IKFpNr1wHiKXajPK0J4IV9lpvykI',
    appId: '1:610579116609:web:72f519ee22b54596844cc0',
    messagingSenderId: '610579116609',
    projectId: 'tubitak-akran-zorbaligi',
    authDomain: 'tubitak-akran-zorbaligi.firebaseapp.com',
    storageBucket: 'tubitak-akran-zorbaligi.firebasestorage.app',
  );

}